name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    paths:
    - "docs/*"

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install ghp-import jupyter-book jupytext

    # Build the page
    - name: Build the book
      run: |
        jupyter-book build docs

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      if: ${{ !env.ACT }}
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
