name: Deploy docker

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
    paths: '.'
    inputs:
      version:
        description: 'Docker push version'     
        required: false
        default: 'unstable'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tigrlab/air-tigrs:unstable
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push manual
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tigrlab/air-tigrs:${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
